### ISSUE TITLE
Code generation doesn't work in 1.3.0 net6

### ISSUE THREAD

**Issue by bazarniy** [MMaximus111/StaticDictionaries#1]
Hi there!

I'm using jetbrains rider (latest version). I have this warning on project build and codegeneration doesn't work:

Не удается загрузить сборку Analyzer C:\Users\Kir\.nuget\packages\staticdictionaries\1.3.0\analyzers\dotnet\cs\StaticDictionaries.dll: Could not load file or assembly 'StaticDictionaries, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null, processorArchitecture=x86'. The given assembly name or codebase was invalid. (0x80131047)

I have AnyCpu and there are NO "prefer x32".

When downgrade to 1.2.0 all works fine

**Comment by MMaximus111** [comment]
Thanks for the referral. I will try to resolve the issue as soon as possible and let you know.

**Comment by MMaximus111** [comment]
Good day, I released 1.3.1-preview1 version with a bug fix. Please check if the bug is reproducible on it, if everything is ok I will make a stable hotfix. 

https://www.nuget.org/packages/StaticDictionaries/1.3.1-preview1

**Comment by MMaximus111** [comment]
Fixed in hotfix 1.3.1

**Comment by bazarniy** [comment]
Thank you very much for fast fix! Works fine for me
